_wandb:
    value:
        cli_version: 0.21.1
        e:
            m1l1o50akviig8gs2kfe7ff65s5glghb:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "4294967296"
                codePath: stream_ac_continuous_OptDesign_prediction.py
                codePathLocal: stream_ac_continuous_OptDesign_prediction.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "574520504320"
                email: a.sharifnassab@gmail.com
                executable: /Users/arsalan/Desktop/Codes/StreamX/streaming-drl-main/.venv/bin/python3
                git:
                    commit: a8e4b0a7b8a03c23830ae126618951caf0f9f851
                    remote: git@github.com:sharifnassab/StreamX_optimizer.git
                host: MacBook-Air-4.local
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/arsalan/Desktop/Codes/StreamX/StreamX_overshoot_prevention/stream_ac_continuous_OptDesign_prediction.py
                python: CPython 3.11.9
                root: /Users/arsalan/Desktop/Codes/StreamX/StreamX_overshoot_prevention
                startedAt: "2025-10-20T17:26:52.795281Z"
                writerId: m1l1o50akviig8gs2kfe7ff65s5glghb
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.9
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
beta2_value:
    value: 0.999
entropy_coeff:
    value: 0.01
entryise_normalization_value:
    value: none
env_name:
    value: Ant-v5
gamma:
    value: 0.99
kappa_policy:
    value: 3
kappa_value:
    value: 2
lamda:
    value: 0
lr:
    value: 1
observer_type:
    value: Obn
seed:
    value: 0
total_steps:
    value: 20000
u_trace_value:
    value: 0.99
